pipeline {
    agent any
    environment {
        DOCKER_HUB_USERNAME = 'pranav224'  // Docker Hub Username
        DOCKER_HUB_ACCESS_TOKEN = credentials('docker_hub_access_token')  // Use Jenkins credentials for the access token
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pranav8722/container-security.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    bat 'docker build -t pranav224/container-security-image:latest -f images/Dockerfile .'
                }
            }
        }
        stage('Scan Docker Image with Trivy') {
            steps {
                script {
                    bat "trivy image pranav224/container-security-image:latest"
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Log in to Docker using Jenkins credentials
                    withCredentials([string(credentialsId: 'docker_hub_access_token', variable: 'DOCKER_HUB_ACCESS_TOKEN')]) {
                        bat "echo %DOCKER_HUB_ACCESS_TOKEN% | docker login -u %DOCKER_HUB_USERNAME% --password-stdin"
                    }
                    bat 'docker push pranav224/container-security-image:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    bat 'kubectl apply -f kubernetes/deployment.yaml'
                }
            }
        }
    }
    post {
        success {
            echo "Pipeline completed successfully."
        }
        failure {
            echo "Pipeline failed. Please check the logs."
        }
    }
}
