pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'secure-app'
        REGISTRY_URL = 'harbor.myorg.com'
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/pranav8722/container-security.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $REGISTRY_URL/$DOCKER_IMAGE:latest .'
            }
        }
        stage('Scan Docker Image') {
            steps {
                sh 'sh scanners/trivy-scan.sh $REGISTRY_URL/$DOCKER_IMAGE:latest'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker push $REGISTRY_URL/$DOCKER_IMAGE:latest'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }
    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
